version: "3"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/media:/vol/web/media
      - ./sample_cinema.json:/app/data/sample_cinema.json
    command: >
      sh -c "mkdir -p /app/data &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata /app/data/sample_cinema.json &&
             python manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    env_file:
      - frontend/.env
